name: my_pytorch_env
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
    - torch==2.5.1+cu121
    - torchvision==0.20.1+cu121
    - torchaudio==2.5.1+cu121
    - tiktoken==0.7.0
